name: Automated Subscription Cleaner

env:
  SRC_1: ${{ secrets.VLESS }}
  SRC_2: ${{ secrets.BL }}
  SRC_3: ${{ secrets.WL }}
  SRC_4: ${{ secrets.BYPASS }}
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_and_clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Download (4 Sources)
        run: |
          curl -sL \
            -o raw_vless.txt "$SRC_1" \
            -o raw_bl.txt "$SRC_2" \
            -o raw_wl.txt "$SRC_3" \
            -o raw_bypass.txt "$SRC_4"
 
      - name: Filter Subs
        run: |
          python3 -c "import sys, urllib.parse; [print(l) for l in sys.stdin.read().splitlines() if urllib.parse.parse_qs(urllib.parse.urlparse(l).query).get('security') == ['reality']]" < raw_vless.txt > reality.txt || true
          python3 -c "import sys, urllib.parse; [print(l) for l in sys.stdin.read().splitlines() if urllib.parse.parse_qs(urllib.parse.urlparse(l).query).get('security') == ['reality']]" < raw_bl.txt > bl.txt || true
          python3 -c "import sys, urllib.parse; [print(l) for l in sys.stdin.read().splitlines() if urllib.parse.parse_qs(urllib.parse.urlparse(l).query).get('security') == ['reality']]" < raw_wl.txt > wl.txt || true
          python3 -c "import sys, urllib.parse; [print(l) for l in sys.stdin.read().splitlines() if urllib.parse.parse_qs(urllib.parse.urlparse(l).query).get('security') == ['reality']]" < raw_bypass.txt > bypass.txt || true
      
      - name: Create sanitized TLS and Reality files
        run: |
          mkdir -p scripts

          python3 scripts/sanitize_vless.py \
            raw_vless.txt \
            vless_clean.txt

          python3 scripts/sanitize_vless.py \
            raw_bl.txt \
            bl_clean.txt

          python3 scripts/sanitize_vless.py \
            raw_wl.txt \
            wl_clean.txt

          python3 scripts/sanitize_vless.py \
            raw_bypass.txt \
            bypass_clean.txt

      - name: Remove raw subscriptions
        run: |
          rm -f \
            raw_vless.txt \
            raw_bl.txt \
            raw_wl.txt \
            raw_bypass.txt

      - name: Commit and Push clean files
        run: |
          git config --global user.name "nick-core-web"
          git config --global user.email "319255208+nick-core-web@users.noreply.github.com"
          
          git add .
          
          if ! git diff --cached --quiet; then
            git commit -m "Update files"
            git push
          else
            echo "No changes to commit"
          fi
